name: bp_monitor
description: "Aplicativo para controle de pressão arterial"
publish_to: 'none'
version: 1.2.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Local Storage
  shared_preferences: ^2.2.3

  #gráficos
  fl_chart: ^1.1.0
  intl: ^0.20.2
  pdf: ^3.10.4
  path_provider: ^2.1.1
  share_plus: ^7.1.0

flutter:
  uses-material-design: true
  # CORREÇÃO: Fontes removidas temporariamente